import Test.Arrow
import Test.Comp
import Test.CoTree
import Test.CombinedFeatures
import Test.Dead
import Test.DeadWrap
import Test.ExplicitTypeAnnotations
import Test.ITreeBaseQpf
import Test.CodataCorec
import Test.CardPFunctor
import Test.CoinductionProtocol
import Test.EquivUTTAbstract
import Test.ComputedFields
import Test.List
import Test.Misc
import Test.MutualInductiveSpec
import Test.MutualCodataSpec
import Test.MutualDataStub
import Test.RecOnCasesOn
import Test.Tree
-- import Test.Variable
import Test.WithBindersInCtor
import Test.Wrap
